# PostgreSQL (Neon Cloud)
spring.datasource.url=jdbc:postgresql://ep-quiet-grass-am0y564p-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_K2cxmB1AGtbV

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

# Thymeleaf
spring.thymeleaf.cache=false

# Security (disable default)
spring.security.user.name=disabled
spring.security.user.password=disabled